### ISSUE TITLE
Use with serde_derive

### ISSUE THREAD

**Issue by Timmmm** [simd-lite/simdjson-rs#101]
Is it possible to use this crate with `serde_derive` to speed up parsing? E.g. currently I have

```
#[derive(Serialize, Deserialize, Debug)]
pub struct Foo {
  pub a: u64,
  pub b: Vec<u64>,
  pub c: Option<u64>,
}
...

  let file = File::open(filename)?;
  let reader = BufReader::new(file);
  let result: Foo = serde_json::from_reader(reader)?
```

Is there a way to do something like this?

```
  let result: Foo = simd_json::from_reader(reader)?
```

**Comment by Licenser** [comment]
Hi Timmmm!

There is `from_slice(&mut [u8])` that will do what you are looking for for the most part. We currently do not have a 'from_reader' interface since simdjson depends on being able to go over the entire data in a go.

I would have to look into if it is possible to wrap a from_reader around it but I'm slightly unsure given we do use the input value for references (this might not affect it, but I don't want to give false hope).

How far does from_slice get you?

https://docs.rs/simd-json/0.2.3/simd_json/serde/fn.from_slice.html

**Comment by Timmmm** [comment]
Ah yes this seems to work!

```
  let file = File::open(filename)?;
  let mut data = Vec::new();
  file.read_to_end(&mut data)?;
  let v: serde_json::Value = simd_json::serde::from_slice(&mut data)?;
  let result = Foo::deserialize(v)?;
```

Might be worth adding to the readme because it wasn't obvious.

Unfortunately this was waaay slower than just using the default Serde implementation for me. Serde is ~4s to read a 185 MB file, this was 9s. Oh well!

**Comment by Licenser** [comment]
Are you compiling your code using native CPU detection settings?

**Comment by Licenser** [comment]
That is either copying the .cargo from this project (or making your own with the flag) or using `RUSTFLAGS="-C target-cpu=native"`

**Comment by Timmmm** [comment]
Yeah I put that in my `.cargo/config` and am compiling with `--release`. I guess converting to `serde_json::Value` and then again to my structs is slower than just reading into the structs directly?

**Comment by Licenser** [comment]
Oh, yes sorry I totally missed that part! I kind of thought you're reading to a Vec then deserialising it.

That explains the speed I'll try to explain:

First you 'pay' for DOM deserialization - which is significantly slower than deserializing a struct since instead of knowing already how the memory layout looks like it will try to piece it together on the fly as the data comes in.

Second `serde_json::Value` isn't particularly fast at that even for DOM serialization.

Then in the third step, you pay again for traversing the entire DOM object to pull out the data to put it in a struct.

If you want to give the `serde-from-reader` branch a try, it should be faster :), a ~200MB struct should :tm: parse in way under a second.

**Comment by Licenser** [comment]
disclaimer for should:

* Disk speeds will affect that
* CPU speed and make will affect that

To ballpark here are some numbers on struct deserialization from the other day. Of cause, this is a benchmark and benchmark always lie but the relation between the numbers should not be too far off (i.e. % of performance improvement).

```
                                DOM                  STRUCT
======= serde_json ======= parse|stringify ===== parse|stringify ====
data/canada.json         270 MB/s   460 MB/s   520 MB/s   370 MB/s
data/citm_catalog.json   400 MB/s   590 MB/s   930 MB/s   830 MB/s
data/twitter.json        290 MB/s   860 MB/s   600 MB/s   860 MB/s
data/log.json            360 MB/s  1080 MB/s   720 MB/s  1080 MB/s

======= simd_json ======== parse|stringify ===== parse|stringify ====
data/canada.json         520 MB/s   480 MB/s   680 MB/s   370 MB/s
data/citm_catalog.json  1070 MB/s   680 MB/s  1570 MB/s   840 MB/s
data/twitter.json        910 MB/s   850 MB/s  1080 MB/s   860 MB/s
data/log.json           1080 MB/s  2170 MB/s  1080 MB/s  1080 MB/s
```

That said I'm not sure how the reader affects the whole thing, I could see serde_json still being faster in the end as it can interleave 'reading' and parsing if rust handles it in a smart way.

if it does we might want to consider adding streaming support (that'd be a lot harder then a from_reader :P) but the goal is to have the fastest JSON parser to rust so it'll definitely get ticketed ;)

**Comment by Timmmm** [comment]
Ah sweet, I will try this next week (on holiday at the moment)! I think actually reading the data in is a trivial amount of time, but streaming does have two important advantages for my use case:

1. It reduces memory use - the biggest JSON file I've had to read so far is 35 GB!
2. It lets me report progress using the following reader:

```
use std::io::{Read, Result};

// Sends progress over a channel while reading.
pub struct ProgressReader<R: Read> {
  // Underlying reader.
  reader: R,
  // Channel to report results.
  channel: crossbeam::Sender<u8>,
  // Previous percent reported.
  reported: Option<u8>,
  // Number of bytes read.
  read: u64,
  // Total size.
  total: u64,
}

impl<R: Read> ProgressReader<R> {
  // It reports every percent, from 0 to 100.
  pub fn new(reader: R, channel: crossbeam::Sender<u8>, total: u64) -> Self {
    Self {
      reader,
      channel,
      reported: None,
      read: 0,
      total,
    }
  }
}

impl<R: Read> Read for ProgressReader<R> {
  fn read(&mut self, buf: &mut [u8]) -> Result<usize> {
    let bytes_read: usize = self.reader.read(buf)?;
    self.read += bytes_read as u64;
    let percent = (100 * self.read / self.total) as u8;
    if Some(percent) != self.reported {
      self.channel.send(percent).expect("Error sending progress to channel");
      self.reported = Some(percent);
    }
    Ok(bytes_read)
  }
}
```

It it were possible to add a streaming mode, or a chunked streaming mode where it reads 10 MB at a time or whatever, that would be very useful.

**Comment by Licenser** [comment]
I think the upstream implementation  (and ours)  caps at 4GB of JSON, the tape building and index keeping will take quite a bit of space (even in a streaming mode). For a 36GB file, unless you've LOTS of memory to spare, I'd suggest a naive parser like serde_json that doesn't require that kind of memory footprint.

As much as I love simd-json this might be one of the use cases where its design makes it badly suited. 

That said it might be investigating, just not a thing done quickly.

**Comment by Timmmm** [comment]
Well, the current machine I'm using has 768 GB of RAM but I probably shouldn't rely on that! :-D I'll check the speed difference anyway.

**Comment by Licenser** [comment]
I was not expecting that :joy: that would make it possible to parse a 36GB file even with the memory amplification caused by the parser. But we'll have to see how that affects other things. I'm curious, what structure does the file have - I suspect you can't give a full detail but is it a huge object with data or an array of many objects?
