### ISSUE TITLE
Performance difference between simdjson-rs and simdjson (C++)

### ISSUE THREAD

**Issue by rohitjoshi** [simd-lite/simdjson-rs#90]
Is there any performance comparison data between this implementation and C++ (https://github.com/lemire/simdjson)

**Comment by Licenser** [comment]
Okay this is more complicated to answer then it sounds.

First of all, every synthetic benchmark is a lie (the ones we have included) not out of bad faith or malice but for the simple reason that a benchmark can never capture the full complexity of a program or the intricate details each use case has.

The very short (and mostly incorrect) answer is yes, somewhat. If you are only looking for pure parsing benchmarks (so nothing happens after that and data is thrown away), [we ran some benchmarks on Nov. 4th](https://twitter.com/heinz_gies/status/1191444292570624001?s=20) 
![image](https://user-images.githubusercontent.com/119093/71118965-64bdc680-21d9-11ea-8929-153cbe085625.png) and you can compare them with upstream.

Canada gets ~1GB/s vs ~0.8MB/s, citm gets ~2.5GB/s vs. ~2GB/s, twitter gets 2GB/s vs. 1.7GB/s.

The simd-json.rs tests are run on a slightly older hardware but I didn't find that to make a significant difference.

This is where the simple part ends because simd-json.rs isn't supposed to be a one to one port for that wrapping the c library would have been the better approach IMHO since the code is excellent, as safe as rust port, and already exists. Also the rust gods demand their performance sacrifice.

That said there are (I hope to be) good reasons for the decision, despite them costing performance while parsing.

First of all parsing isn't where the life cycle of most JSON data ends. Upstream simdjson does not provide mutability, and that's OK it's outside of the scope of it. In contrast it is something we really wanted for simd-json.rs as in our eyes it increases the usefulness immensely.


Second is inspection, the tape used in upstream simdjson is usable having a nested DOM with lookup and introspection functions feels like a big ergonomic win. We also put effort in making this codepath fast - sometimes at the cost of parsing (for example the `known-keys` feature).

The second bit goal was forming well into the rust ecosystem. That goes back to the DOM as well as the serde integration that lets you parse right to rust structs. Ther

So what's the bottom line? That to compare you probably need to decide what you do with the data. Also what you want to invest in programmer time in it. 

My prediction without data to back them up:

* I am nearly certain that if you don't mind writing more code forking simdjson (upstream) and hard coding your decoding into data in it is going to win hand down over both simdjson and simd-json.rs. If you 
* If you just parse data but nothing else, simdjson will be faster hands down (we got data for that!)
* If you want to look and inspect your data it gets a lot more complicated, as it depends on how the data is structured, how you access the data, if access is repeated or one time and how much time you feel about investing optimizing access
* Lastly if you need to modify data it again comes to how much you feel like investing timewise, simdjson itself doesn't provide a facility to it, of cause you can write that yourself but otherwise simd-json.rs clearly seems a better choice here.

I hope that makes sense? If not, we're open to include any benchmark, good or bad  :)

**Comment by rohitjoshi** [comment]
Thank you for the details answer and great work !
